name = "HarderNarasimhan"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HarderNarasimhan"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.25.1"

[[lean_lib]]
name = "HarderNarasimhan"
